# Generated by Django 4.2.4 on 2023-11-03 09:53

from django.db import migrations, models
import file_validator.models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(max_length=200, unique=True, verbose_name="Titre"),
                ),
                ("batch", models.IntegerField(default=1, verbose_name="Numéro de Lot")),
                (
                    "illustration",
                    models.ImageField(
                        blank=True,
                        upload_to="photos/",
                        validators=[
                            file_validator.models.DjangoFileValidator(
                                acceptable_mimes=[
                                    "image/png",
                                    "image/jpeg",
                                    "image/jpg",
                                    "image/webp",
                                ],
                                acceptable_types=["image"],
                                libraries=["python_magic", "filetype"],
                                max_upload_file_size=5242880,
                            )
                        ],
                    ),
                ),
                (
                    "illustation_footnote",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Note sur l'illustration",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True, max_length=1000, verbose_name="Verso de la carte"
                    ),
                ),
            ],
        ),
    ]
