# Generated by Django 4.2.4 on 2023-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(max_length=200, unique=True, verbose_name="Titre"),
        ),
    ]
