# Generated by Django 4.2.4 on 2023-11-03 10:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0003_alter_card_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="content",
            field=tinymce.models.HTMLField(
                blank=True, max_length=3000, verbose_name="Verso de la carte"
            ),
        ),
    ]
