# Generated by Django 4.2.4 on 2023-11-03 10:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0004_alter_card_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="content",
            field=tinymce.models.HTMLField(
                blank=True, max_length=10000, verbose_name="Verso de la carte"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="illustation_footnote",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Note sur l'illustration"
            ),
        ),
    ]
