# Generated by Django 4.2.4 on 2023-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0005_alter_card_content_alter_card_illustation_footnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_number",
            field=models.IntegerField(
                blank=True, default=1, verbose_name="Numéro de carte dans le lot"
            ),
            preserve_default=False,
        ),
    ]
