# Generated by Django 4.2.4 on 2023-11-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0007_alter_card_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Nom du Lot"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(default=1, verbose_name="Numéro de Lot"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="batch_foreign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cardfactory.batch",
            ),
        ),
    ]
