# Generated by Django 4.2.4 on 2023-11-10 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0008_batch_card_batch_foreign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="batch_foreign",
            new_name="lot",
        ),
        migrations.RemoveField(
            model_name="card",
            name="batch",
        ),
    ]
