# Generated by Django 4.2.4 on 2023-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0009_rename_batch_foreign_card_lot_remove_card_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="batch",
            field=models.IntegerField(blank=True, default=1, verbose_name="batch"),
        ),
    ]
