# Generated by Django 4.2.4 on 2023-11-30 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardfactory", "0010_card_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="batch",
        ),
    ]
